=== meriosol/etr/projects/xmlius/etr_xsl/src/xsl/etr_prototype.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://com/meriosol/etr/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://com/meriosol/etr/schema" elementFormDefault="qualified"
        attributeFormDefault="unqualified" version="v1_PROTOTYPE" id="ETR_PROTOTYPE_20140404">
    <annotation>
        <documentation xml:lang="en">
            This schema represents Event Tracker (ETR) XML validation rules.
        </documentation>
    </annotation>

    <element name="event">
        <annotation>
            <documentation xml:lang="en">
                Event data.
            </documentation>
        </annotation>

        <complexType>
            <all>
                <element ref="tns:event-category" minOccurs="0" maxOccurs="1"/>
                <element name="source" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <element name="process-id" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </all>
            <attribute name="id" use="required" type="xs:long">
                <annotation>
                    <documentation xml:lang="en">
                        Notice ID is mandatory attribute
                        , but because backend can generate own value, change of this ID value is expected thing.
                    </documentation>
                </annotation>
            </attribute>
            <attribute name="severity" use="optional">
                <annotation>
                    <documentation xml:lang="en">
                        Severity describes how good or bad things are.
                        Notice: for now there is enumeration below, but in real life this list can be more flexible.
                    </documentation>
                </annotation>
                <simpleType>
                    <restriction base="NMTOKEN">
                        <enumeration value="INFO"/>
                        <enumeration value="WARN"/>
                        <enumeration value="ERROR"/>
                    </restriction>
                </simpleType>
            </attribute>
            <attribute name="created" use="optional" type="xs:dateTime">
                <annotation>
                    <documentation xml:lang="en">
                        Date when Event added into backend.
                    </documentation>
                </annotation>
            </attribute>
        </complexType>
    </element>

    <element name="event-category">
        <annotation>
            <documentation xml:lang="en">
                Event category.
            </documentation>
        </annotation>

        <complexType>
            <all>
                <element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            </all>
            <attribute name="code" use="required" type="xs:token">
                <annotation>
                    <documentation xml:lang="en">
                        Category code.
                    </documentation>
                </annotation>
            </attribute>
        </complexType>
    </element>

    <element name="events">
        <complexType>
            <sequence>
                <element ref="tns:event" minOccurs="0" maxOccurs="1000000"/>
            </sequence>
        </complexType>
        <key name="eventUniqueKey">
            <selector xpath="./tns:event"/>
            <field xpath="@id"/>
        </key>
    </element>

    <element name="event-categories">
        <complexType>
            <sequence>
                <element ref="tns:event-category" minOccurs="0" maxOccurs="1000"/>
            </sequence>
        </complexType>
        <key name="eventCategoryUniqueKey">
            <selector xpath="./tns:event-category"/>
            <field xpath="@code"/>
        </key>
    </element>


</schema>

=== meriosol/etr/projects/xmlius/etr_jaxb/src/xml/sample_incorrect_events.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<events xmlns="http://com/meriosol/etr/schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://com/meriosol/etr/schema etr_prototype.xsd">
    <event id="1000001" severity="INFO" created="2014-04-04T01:02:03.231Z">
        <event-category code="MESSAGE">
            <name>Message</name>
        </event-category>
        <source>SRC1</source>
        <process-id>PRC1</process-id>
        <title>Some INFO message</title>
    </event>
    <event id="1000001" severity="WARN_WRONG" created="2014-04-04T01:02--04.234Z">
        <event-category code="MESSAGE"/>
        <source>SRC2</source>
        <process-id>PRC 2</process-id>
        <title>Some WARN message</title>
    </event>
    <event severity="INFO" created="2014-04-04T01:16:04.234Z">
        <event-category code="MESSAGE"/>
        <source>SRC3</source>
        <process-id>PRC_3</process-id>
    </event>
</events>

=== meriosol/etr/projects/xmlius/etr_xsl/src/xsl/sample_events.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="eventium_grid.xsl"?>
<events xmlns="http://com/meriosol/etr/schema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://com/meriosol/etr/schema etr_prototype.xsd">
    <event id="1000001" severity="INFO" created="2014-04-04T01:02:03.231Z">
        <event-category code="MESSAGE">
            <name>Message</name>
        </event-category>
        <source>SRC451</source>
        <process-id>PRC1</process-id>
        <title>Some INFO message</title>
    </event>
    <event id="1000002" severity="WARN" created="2014-04-04T01:02:04.234Z">
        <event-category code="MESSAGE"/>
        <source>SRC451</source>
        <process-id>PRC1</process-id>
        <title>Some WARN message</title>
    </event>
    <event id="1000003" severity="ERROR" created="2014-04-07T01:02:04.234Z">
        <event-category code="ALERT"/>
        <source>SRC778</source>
        <process-id>PRC2</process-id>
        <title>Some ERROR message</title>
    </event>
    <event id="1000004" severity="ERROR" created="2014-04-07T01:02:04.899Z">
        <event-category code="ALERT">
            <name>Alertius</name>
        </event-category>
        <source>SRC718</source>
        <process-id>PRC2</process-id>
        <title>Some more ERROR message</title>
    </event>

</events>
